//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtobaza.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilety
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bilety()
        {
            this.Oplata = new HashSet<Oplata>();
        }
    
        public int IDBileta { get; set; }
        public int IDReysa { get; set; }
        public int IDClienta { get; set; }
        public string NomerMesta { get; set; }
        public System.DateTime DataIVremyaOtpravleniya { get; set; }
        public System.DateTime DataIVremyaPribytiya { get; set; }
        public decimal Stoimost { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Reysy Reysy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oplata> Oplata { get; set; }
    }
}
