//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtobaza.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oplata
    {
        public int IDOplaty { get; set; }
        public int IDBileta { get; set; }
        public System.DateTime DataOplaty { get; set; }
        public string Sposob { get; set; }
    
        public virtual Bilety Bilety { get; set; }
    }
}
