//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtobaza.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reysy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reysy()
        {
            this.Bilety = new HashSet<Bilety>();
        }
    
        public int IDReysa { get; set; }
        public int IDTransporta { get; set; }
        public string NomerReysa { get; set; }
        public int IDMarshruta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilety> Bilety { get; set; }
        public virtual Marshruty Marshruty { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
