//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspisanie
    {
        public int IDraspisaniya { get; set; }
        public int IDMarshtuta { get; set; }
        public string DenNedeli { get; set; }
        public System.TimeSpan VremyaOtpravleniya { get; set; }
        public System.TimeSpan VremyaPribytiya { get; set; }
        public Nullable<System.TimeSpan> IntervalyDvizheniya { get; set; }
    
        public virtual Marshruty Marshruty { get; set; }
    }
}
